import React from 'react';
import { linePoints, type LineProfile } from '../../engine/model/linePath';

/**
 * A specimen of each line profile, generated by the profile itself.
 *
 * The same argument the sketch and end-cap specimens make: a hand-drawn glyph
 * for "coil" is a guess at what the code produces, and the moment the profile
 * is retuned the guess is wrong with nothing to catch it. These call
 * `linePoints` — what the canvas calls — so the button is a small version of
 * the line it draws.
 *
 * Two repeats rather than the default six: at 20px the default is a blur, and
 * the point of the glyph is to say *what shape* the run makes, not how often.
 */
const W = 22;
const H = 14;

export const LineProfileIcon: React.FC<{ profile: LineProfile }> = ({ profile }) => {
  const pts = linePoints({ x: 1.5, y: H / 2 }, { x: W - 1.5, y: H / 2 }, profile, 2);
  const d = pts.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(' ');
  return (
    <svg width={W} height={H} viewBox={`0 0 ${W} ${H}`} aria-hidden="true" focusable="false">
      <path
        d={d}
        fill="none"
        stroke="currentColor"
        strokeWidth="1.4"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
};
